import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/views/Navbar'
import { Roboto } from 'next/font/google'
import Footer from '@/components/views/Footer'

const inter = Roboto({ 
  subsets: ['latin'],
  weight: ["400", "500", "700", "900"]
})

export const metadata: Metadata = {
  title: 'Ecommerce Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}</body>
        <Footer/>
    </html>
  )
}
